services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./volumes/game_data:/game_data:z

  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./volumes/game:/usr/share/nginx/html:z
    depends_on:
      - api


volumes:
  game_data:
  game:
